* GfyKeys

This thing popped up on Hacker News:

https://github.com/zevv/bucklespring/blob/master/README.md

I wondered what it was like, so I ran it - but it didn't seem to work
on Windows 10.

What better solution to this problem than just to rewrite the whole
thing?

* Use

1. Run =GfyKeys_Release.exe=

2. Enjoy (?)

To shut it down, kill it with Task Manager.

* Build

Use Visual Studio 2015.

* Licence

As per the original:

The MIT License (MIT)

Copyright (c) 2016 - Ico Doornekamp, Tom Seddon

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
